In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("../data/raw/kat_raw.csv")
df.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max
0,2024-09-01,24.5,19.6,22.0,26.1,7.6
1,2024-09-02,26.6,18.6,21.9,3.9,6.5
2,2024-09-03,28.3,18.6,22.0,6.7,8.7
3,2024-09-04,25.7,18.7,21.8,5.8,10.1
4,2024-09-05,26.4,18.8,22.1,18.3,5.0

In [9]:
print("info:"); df.info()

print("missing count:") ; df.isna().sum()   # missing count per column


print("describe:"); df.describe()

info:
<class 'pandas.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 760 non-null    str
 1   temperature_2m_max   760 non-null    float64
 2   temperature_2m_min   760 non-null    float64
 3   temperature_2m_mean  760 non-null    float64
 4   precipitation_sum    760 non-null    float64
 5   wind_speed_10m_max   760 non-null    float64
dtypes: float64(5), str(1)
memory usage: 35.8 KB
missing count:
describe:

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max
count,760.000000,760.000000,760.000000,760.000000,760.000000
mean,23.788553,14.142632,18.415395,7.318421,8.839079
std,3.665024,5.397247,4.308295,13.691299,2.422487
min,14.000000,1.900000,8.800000,0.000000,4.200000
25%,20.575000,9.200000,14.400000,0.000000,7.000000
50%,24.550000,15.100000,19.450000,1.800000,8.500000
75%,27.000000,19.100000,22.300000,9.400000,10.200000
max,30.600000,21.700000,24.500000,191.100000,21.100000

In [10]:
(df["temperature_2m_min"] > df["temperature_2m_max"]).sum()   # should be 0

df[df["precipitation_sum"] > 50]   # change 50 to whatever threshold you choose

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max
26,2024-09-27,20.6,18.7,19.4,191.1,8.6
27,2024-09-28,20.2,18.2,18.9,112.6,9.3
328,2025-07-26,26.6,20.1,23.3,66.7,5.1
330,2025-07-28,25.0,21.4,22.4,64.6,5.3
346,2025-08-13,25.3,21.3,22.4,51.1,6.6
398,2025-10-04,20.2,16.9,18.3,90.9,9.4
679,2026-07-12,27.6,21.1,23.2,56.0,7.8
680,2026-07-13,24.6,21.5,22.6,91.9,6.3
754,2026-09-25,18.7,16.9,17.9,56.5,9.5

### consistent column names

In [11]:
df = df.rename(
    columns={
        "time": "date",
        "temperature_2m_max": "temp_max_c",
        "temperature_2m_min": "temp_min_c",
        "temperature_2m_mean": "temp_mean_c",
        "precipitation_sum": "rain_mm",
        "wind_speed_10m_max": "wind_max_kmh",
    }
)

### save the cleaned files

In [12]:
import os
os.makedirs("../data/clean", exist_ok=True)
df.to_csv("../data/clean/kat_clean.csv", index=False)