In [29]:
import pandas as pd

In [30]:
df = pd.read_csv("../data/raw/kat_2026-09_raw.csv")
df.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max
0,2026-09-01,26.6,20.9,22.9,33.4,6.5
1,2026-09-02,26.7,20.8,22.3,42.4,4.7
2,2026-09-03,25.2,20.1,22.0,34.6,4.8
3,2026-09-04,27.0,19.7,21.9,36.2,7.3
4,2026-09-05,27.1,19.5,21.9,31.5,6.0

In [31]:
df['time'] = pd.to_datetime(df["time"])
print("info:"); df.info()

print("missing count:") ; df.isna().sum()   # missing count per column


print("describe:"); df.describe()

info:
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 30 non-null     datetime64[us]
 1   temperature_2m_max   30 non-null     float64
 2   temperature_2m_min   30 non-null     float64
 3   temperature_2m_mean  30 non-null     float64
 4   precipitation_sum    30 non-null     float64
 5   wind_speed_10m_max   30 non-null     float64
dtypes: datetime64[us](1), float64(5)
memory usage: 1.5 KB
missing count:
describe:

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max
count,30,30.000000,30.000000,30.000000,30.000000,30.00000
mean,2026-09-15 12:00:00,25.650000,18.713333,21.373333,16.843333,6.92000
min,2026-09-01 00:00:00,18.700000,16.400000,17.900000,2.000000,4.60000
25%,2026-09-08 06:00:00,25.225000,17.925000,21.200000,5.100000,5.82500
50%,2026-09-15 12:00:00,26.450000,18.550000,21.600000,12.150000,6.65000
75%,2026-09-22 18:00:00,26.800000,19.650000,21.975000,28.875000,7.82500
max,2026-09-30 00:00:00,27.900000,20.900000,22.900000,56.500000,12.00000
std,NaN,2.037874,1.168770,1.022146,14.488989,1.76213

In [34]:
(df["temperature_2m_min"] > df["temperature_2m_max"]).sum()   # should be 0

df[df["precipitation_sum"] > 50]   # change 50 to whatever threshold you choose

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max
24,2026-09-25,18.7,16.9,17.9,56.5,9.5

### consistent column names

In [37]:
df = df.rename(
    columns={
        "time": "date",
        "temperature_2m_max": "temp_max_c",
        "temperature_2m_min": "temp_min_c",
        "temperature_2m_mean": "temp_mean_c",
        "precipitation_sum": "rain_mm",
        "wind_speed_10m_max": "wind_max_kmh",
    }
)

### save the cleaned files

In [38]:
import os
os.makedirs("../data/clean", exist_ok=True)
df.to_csv("../data/clean/kat_september_clean.csv", index=False)